---
- name: Deployment of Genre Classification application
  hosts: all
  become: yes
  vars:
    remote_dir: "/home/ubuntu/genre_clf"
    local_files:
      - "genre_clf/server/requirements.txt"
      - "genre_clf/server/app.py"
      - "genre_clf/server/utils/feature_extraction.py"
      - "genre_clf/server/model/min_max_scaler.pkl"
      - "genre_clf/server/model/xgb_mgen.pkl"
      - "genre_clf/server/templates/index.html"
      - "genre_clf/server/templates/result.html"
  tasks:

    - name: Ensure the target directory exists
      ansible.builtin.file:
        path: "{{ remote_dir }}"
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Copy files to remote server
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ remote_dir }}/"
      loop: "{{ local_files }}"
    
    - name: Go to the directory genre_clf/server
      ansible.builtin.shell: 
        cmd: cd {{ remote_dir}}/server
        
    - name: Update files
      ansible.builtin.shell: 
        cmd: sudo apt update
        
    - name: Install python
      ansible.builtin.shell: 
        cmd: sudo apt install python3-pip

    - name: Install all requirement
      ansible.builtin.shell: 
        cmd: pip install -r requirements.txt

    - name: Start python file
      ansible.builtin.shell: 
        cmd: python3 app.py
