---
- name: Deployment of Genre Classification application
  hosts: all
  become: yes
  vars:
    remote_dir: "/home/ubuntu/genre_clf"
    local_files:
      - "server/requirements.txt"
      - "server/app.py"
      - "server/utils/feature_extraction.py"
      - "server/model/min_max_scaler.pkl"
      - "server/model/xgb_mgen.pkl"
      - "server/templates/index.html"
      - "server/templates/result.html"
  tasks:

    - name: Ensure the target directory exists
      ansible.builtin.file:
        path: "{{ remote_dir }}"
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Copy files to remote server
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ remote_dir }}/"
      loop: "{{ local_files }}"

    - name: Update
      ansible.builtin.shell: 
        cmd: sudo apt update
        
    - name: Install python
      ansible.builtin.shell: 
        cmd: sudo apt install python3-pip

    - name: Install all requirement
      ansible.builtin.shell: 
        cmd: pip install -r genre_clf/requirements.txt

    - name: Start python file
      ansible.builtin.shell: 
        cmd: python3 ~/genre_clf/app.py
